#!/bin/bash

dialog_root="${3}Library/Application Support/Dialog"
iconfile="${dialog_root}/Dialog.png"
dialogbundle="${dialog_root}/Dialog.app"
localisedbundle="${dialog_root}/Dialog.localized/Dialog.app"
dialogbinary="${dialogbundle}/Contents/MacOS/Dialog"
dialogcli="${dialogbundle}/Contents/MacOS/dialogcli"
log_file="${dialog_root}/postinstall.log"

write_to_log() {
    local message="$1"
    local date="$(date +'%Y-%m-%d %H:%M:%S')"
    echo "[${date}] ${message}" >> "${log_file}"
}

write_to_log "swiftDialog postinstall started"
write_to_log "Installed version: $("${dialogbinary}" --version)"

# Check what the latest available version is and records it in the install log
# fetches json from swiftdialog.app
# json format is {"version":"x.y.z","released":"yyyy-mm-ddThh:mm:ssZ"}
sd_json_data=$(/usr/bin/curl -sL https://beta.swiftdialog.app/version.json)
sd_latest_version=$(echo $sd_json_data | /usr/bin/jq -r '.version' 2>/dev/null)
sd_release_date=$(echo $sd_json_data | /usr/bin/jq -r '.released' 2>/dev/null)
if [[ -n $sd_latest_version ]]; then
    write_to_log "Latest release : $sd_latest_version"
    write_to_log "Release date   : $(date -jf "%Y-%m-%dT%H:%M:%SZ" "$sd_release_date" "+%Y-%m-%d")"
else
    write_to_log "Latest version could not be determined."
fi

# Check for Dialog.localized. If it exists we need to move a few things

if [[ -e "${localisedbundle}" ]]; then
    write_to_log "Localised bundle found. Probably becasue the bundleID of Dialog.app changed"
    if [[ -e "${dialogbundle}" ]]; then
        write_to_log "Old Dialog bundle found. Removing"
        rm -r "${dialogbundle}"
    fi
    write_to_log "Moving ${localisedbundle} to ${dialogbundle}"
    mv "${localisedbundle}" "${dialogbundle}"
    write_to_log "Moved. Hopefully we're good now"
    rm -r "${dialog_root}/Dialog.localized"
fi

if [[ -e "${iconfile}" ]] && [[ -e "${dialogbundle}" ]]; then
    write_to_log "Icon file detected. Updating dialog icon"
    "${dialogbinary}" --seticon "${iconfile}" >> "${log_file}"
    if [[ $? == 0 ]]; then
        write_to_log "Icon update success"
    else
        write_to_log "Icon update failed"
    fi
fi

# create /usr/local/bin/dialog symlink
"${dialogcli}" --link >> "${log_file}"

write_to_log "swiftDialog postinstall complete"
