#!/bin/bash

base_dir="${PWD}"

dialog_root="$3/Library/Application Support/Dialog"
iconfile="${dialog_root}/Dialog.png"
dialogbundle="${dialog_root}/Dialog.app"
localisedbundle="${dialog_root}/Dialog.localized/Dialog.app"
dialogbinary="${dialogbundle}/Contents/MacOS/Dialog"
enrolmentScript="${dialog_root}/swiftDialogEnrolment.sh"
log_file="${dialog_root}/postinstall.log"

write_to_log() {
    local message="$1"
    local date="$(date +'%Y-%m-%d %H:%M:%S')"
    echo "[${date}] ${message}" >> "${log_file}"
}

write_to_log "swiftDialog postinstall started"
write_to_log "swiftDialog $("${dialogbinary}" --version)"

# Check for Dialog.localized. If it exists we need to move a few things

if [[ -e "${localisedbundle}" ]]; then
    write_to_log "Localised bundle found. Probably becasue the bundleID of Dialog.app changed"
    if [[ -e "${dialogbundle}" ]]; then
        write_to_log "Old Dialog bundle found. Removing"
        rm -r "${dialogbundle}"
    fi
    write_to_log "Moving ${localisedbundle} to ${dialogbundle}"
    mv "${localisedbundle}" "${dialogbundle}"
    write_to_log "Moved. Hopefully we're good now"
    rm -r "${dialog_root}/Dialog.localized"
fi

if [[ -e "${iconfile}" ]] && [[ -e "${dialogbundle}" ]]; then
    write_to_log "Icon file detected. Updating dialog icon"
    "${dialogbinary}" --seticon "${iconfile}" >> "${log_file}"
    if [[ $? == 0 ]]; then
        write_to_log "Icon update success"
    else
        write_to_log "Icon update failed"
    fi
fi

write_to_log "swiftDialog postinstall complete"
